### ISSUE TITLE
用户主页的批量爬取？

### ISSUE THREAD

**Issue by Chopin68** [littlePig-zzf/python-demo#1]
根据user/profile后面的特殊id进行批量抓取原图

**Comment by littlePig-zzf** [comment]
不是，目前就是图文的小红书帖子抓取原图

**Comment by Chopin68** [comment]
> 不是，目前就是图文的小红书帖子抓取原图

有思路吗，如果要获取主页下的所有笔记

**Comment by littlePig-zzf** [comment]
> > 不是，目前就是图文的小红书帖子抓取原图
> 
> 有思路吗，如果要获取主页下的所有笔记

暂时还没有好的思路

**Comment by Chopin68** [comment]
尝试用selenium登录后访问指定user的profile之后下滑获取每个笔记的链接，但是好像并没返回，网页上的api也还没找到适合的方式去请求，期待进一步开发

**Comment by littlePig-zzf** [comment]
> 尝试用selenium登录后访问指定user的profile之后下滑获取每个笔记的链接，但是好像并没返回，网页上的api也还没找到适合的方式去请求，期待进一步开发

我刚也有想用selenium试试动态抓取数据，然后拼接链接去抓取，我先试试

**Comment by LvLH** [comment]
直接网页就可以获取主页的信息了啊

**Comment by littlePig-zzf** [comment]
> 尝试用selenium登录后访问指定user的profile之后下滑获取每个笔记的链接，但是好像并没返回，网页上的api也还没找到适合的方式去请求，期待进一步开发

看redBookPatchAll.py文件
