### ISSUE TITLE
关于cookie

### ISSUE THREAD

**Issue by daxiongpro** [littlePig-zzf/python-demo#2]
作者你好，请问如何获取自己的cookie？
我F12打开，点击“应用程序“，发现有很多不同的cookie

**Comment by littlePig-zzf** [comment]
> 作者你好，请问如何获取自己的cookie？ 我F12打开，点击“应用程序“，发现有很多不同的cookie

<img width="793" alt="image" src="https://user-images.githubusercontent.com/25496826/227761540-1b141e52-dcda-433a-afd5-d13e15a60679.png">
随便点击一个接口请求, 看请求头的cookie

**Comment by daxiongpro** [comment]
Thank you so much for your quick reply and your excellent code！
